title: "IAS Blog"
description: "Master's blog on AI and society"
theme: jekyll-theme-minimal  # You can choose a theme or create your own layout
permalink: /:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
