title: "IAS Blog"
description: "Master's blog on AI and society"
theme: minima          # or another GitHub Pagesâ€“supported theme
permalink: /:year/:month/:day/:title/
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
