title: "IAS Blog"
description: "Master's blog on AI and society"
baseurl: "/IAS_2"
url: "https://victortomas09.github.io"
theme: jekyll-theme-minimal
permalink: /:year/:month/:day/:title/

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true