title: "IAS Blog"
description: "Master's blog on AI and society"
theme: minima          # or another GitHub Pagesâ€“supported theme
permalink: /:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
include:
  - _posts
  - _pages
head:
  - '<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>'

